services:
  app_proxy:
    environment:
      APP_HOST: kwapisz-torrentio-proxy_server_1
      APP_PORT: 8080
      PROXY_AUTH_ADD: "false"

  server:
    image: ghcr.io/kacperkwapisz/torrentio-proxy:latest
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TOKEN: "very-secret-string-change-me"
      CACHE_TTL: 10m
      LOG_LEVEL: info