version: "3.7"

services:

  app_proxy:
    ports:
      - "3000:3000"
    environment:
      APP_HOST: kwapisz-auto-unrar_server_1
      APP_PORT: 3000
      PROXY_AUTH_ADD: "false"

  server:
    image: nicxx2/auto-unrar:latest
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - SOURCE_DIRECTORY=/data
      - SLEEP_TIME=3600
      # - OVERWRITE_FILES=false # Set to true to overwrite existing files during extraction
      # - DO_NOT_USE_MARKERS=false # Set to true to ignore markers and extract all archives
      # - EXTRACT_TO_DIRECTORY=/extract_to #Optional
      # - DELETE_RAR_AFTER_EXTRACTION=false # Set to true to delete RAR files post-extraction
    volumes:
      - ${APP_DATA_DIR}/data:/data
      # - /path/to/your/directory/to/add/extracted/data:/extract_to  # Optional: Specify a directory for extracted files
