version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: kwapisz-ownfoil_server_1
      APP_PORT: 8465
      PROXY_AUTH_ADD: "false"

  server:
    image: a1ex4/ownfoil
    restart: on-failure
    user: "1000:1000"
    init: true
    volumes:
      - ${APP_DATA_DIR}/games:/games
      - ${APP_DATA_DIR}/config:/app/config