version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: kwapisz-ownfoil_ownfoil_1
      APP_PORT: 8465

  ownfoil:
    image: a1ex4/ownfoil
    container_name: ownfoil
    user: "1000:1000"
    init: true
    volumes:
      - ./volumes/games:/games
      - ./volumes/config:/app/config